### ISSUE TITLE
RSS or ATOM feed for blog posts

### ISSUE THREAD

**Issue by joschi** [stitchfix/stitchfix.github.io#1]
I'd love to subscribe to your blog posts using my Favorite Feed Reader™ but there doesn't seem to be any RSS or ATOM feed I could subscribe to.

Using Jekyll it should be relatively easy to add an ATOM or RSS feed to the site, e. g. with the [Jekyll Plugin: RSS Feed Generator](https://github.com/agelber/jekyll-rss).

**Comment by bf4** [comment]
http://technology.stitchfix.com/blog/atom.xml 404's.  https://github.com/stitchfix/stitchfix.github.io/blob/86b309898f9fcf99e1cdf02531c2b5041b86b5e9/blog/atom.xml seems to have been removed in https://github.com/stitchfix/stitchfix.github.io/commit/8b8892cae924bf21cb1b19bbe00912735121a31c
