### ISSUE TITLE
Blog feed 404's

### ISSUE THREAD

**Issue by bf4** [stitchfix/stitchfix.github.io#103]
http://technology.stitchfix.com/blog/atom.xml 404's.  https://github.com/stitchfix/stitchfix.github.io/blob/86b309898f9fcf99e1cdf02531c2b5041b86b5e9/blog/atom.xml seems to have been removed in https://github.com/stitchfix/stitchfix.github.io/commit/8b8892cae924bf21cb1b19bbe00912735121a31c

ref #1

**Comment by davetron5000** [comment]
New site up and has a bona-fide feed.  Cannot believe we didn't have one before :(
